export type LocationInfo = { slug:string; name:string; short:string; rate:number; noTax?:boolean; city?:boolean; aliases:string[]; seoName?:string };

export const locations: LocationInfo[] = [
  {slug:"alabama-paycheck-calculator",name:"Alabama",short:"AL",rate:5,aliases:["alabama paycheck calculator"]},
  {slug:"arizona-paycheck-calculator",name:"Arizona",short:"AZ",rate:2,aliases:["arizona paycheck calculator","az paycheck calculator"]},
  {slug:"arkansas-paycheck-calculator",name:"Arkansas",short:"AR",rate:3.7,aliases:["arkansas paycheck calculator"]},
  {slug:"california-paycheck-calculator",name:"California",short:"CA",rate:6,aliases:["california paycheck calculator","ca paycheck calculator","paycheck calculator california"]},
  {slug:"colorado-paycheck-calculator",name:"Colorado",short:"CO",rate:4.4,aliases:["colorado paycheck calculator","paycheck calculator colorado"]},
  {slug:"connecticut-paycheck-calculator",name:"Connecticut",short:"CT",rate:5,aliases:["ct paycheck calculator"]},
  {slug:"florida-paycheck-calculator",name:"Florida",short:"FL",rate:0,noTax:true,aliases:["florida paycheck calculator","fl paycheck calculator","paycheck calculator florida"]},
  {slug:"georgia-paycheck-calculator",name:"Georgia",short:"GA",rate:4.99,aliases:["georgia paycheck calculator","ga paycheck calculator","paycheck calculator georgia"]},
  {slug:"hawaii-paycheck-calculator",name:"Hawaii",short:"HI",rate:7,aliases:["hawaii paycheck calculator"]},
  {slug:"idaho-paycheck-calculator",name:"Idaho",short:"ID",rate:5.3,aliases:["idaho paycheck calculator"]},
  {slug:"illinois-paycheck-calculator",name:"Illinois",short:"IL",rate:4.95,aliases:["illinois paycheck calculator","paycheck calculator illinois"]},
  {slug:"indiana-paycheck-calculator",name:"Indiana",short:"IN",rate:2.95,aliases:["indiana paycheck calculator","paycheck calculator indiana"]},
  {slug:"iowa-paycheck-calculator",name:"Iowa",short:"IA",rate:3.8,aliases:["iowa paycheck calculator"]},
  {slug:"kansas-paycheck-calculator",name:"Kansas",short:"KS",rate:5.7,aliases:["kansas paycheck calculator"]},
  {slug:"kentucky-paycheck-calculator",name:"Kentucky",short:"KY",rate:3.5,aliases:["kentucky paycheck calculator","ky paycheck calculator"]},
  {slug:"louisiana-paycheck-calculator",name:"Louisiana",short:"LA",rate:3.09,aliases:["louisiana paycheck calculator"]},
  {slug:"maryland-paycheck-calculator",name:"Maryland",short:"MD",rate:4.75,aliases:["maryland paycheck calculator","paycheck calculator maryland"]},
  {slug:"massachusetts-paycheck-calculator",name:"Massachusetts",short:"MA",rate:5,aliases:["massachusetts paycheck calculator","mass paycheck calculator"]},
  {slug:"michigan-paycheck-calculator",name:"Michigan",short:"MI",rate:4.25,aliases:["michigan paycheck calculator","paycheck calculator michigan"]},
  {slug:"minnesota-paycheck-calculator",name:"Minnesota",short:"MN",rate:6.8,aliases:["minnesota paycheck calculator","mn paycheck calculator","paycheck calculator mn"]},
  {slug:"missouri-paycheck-calculator",name:"Missouri",short:"MO",rate:4.7,aliases:["missouri paycheck calculator","paycheck calculator missouri"]},
  {slug:"north-carolina-paycheck-calculator",name:"North Carolina",short:"NC",rate:4.09,aliases:["north carolina paycheck calculator","nc paycheck calculator","paycheck calculator nc"]},
  {slug:"nebraska-paycheck-calculator",name:"Nebraska",short:"NE",rate:5.2,aliases:["nebraska paycheck calculator"]},
  {slug:"nevada-paycheck-calculator",name:"Nevada",short:"NV",rate:0,noTax:true,aliases:["nevada paycheck calculator"]},
  {slug:"new-jersey-paycheck-calculator",name:"New Jersey",short:"NJ",rate:5.5,aliases:["new jersey paycheck calculator","nj paycheck calculator","paycheck calculator nj"]},
  {slug:"new-york-paycheck-calculator",name:"New York",short:"NY",rate:6,aliases:["new york paycheck calculator","ny paycheck calculator","nys paycheck calculator"]},
  {slug:"nyc-paycheck-calculator",name:"New York City",short:"NYC",rate:9.88,city:true,aliases:["nyc paycheck calculator","paycheck calculator nyc"]},
  {slug:"ohio-paycheck-calculator",name:"Ohio",short:"OH",rate:3,aliases:["ohio paycheck calculator","paycheck calculator ohio"]},
  {slug:"oklahoma-paycheck-calculator",name:"Oklahoma",short:"OK",rate:4.5,aliases:["oklahoma paycheck calculator"]},
  {slug:"oregon-paycheck-calculator",name:"Oregon",short:"OR",rate:7.5,aliases:["oregon paycheck calculator"]},
  {slug:"pennsylvania-paycheck-calculator",name:"Pennsylvania",short:"PA",rate:3.07,aliases:["pennsylvania paycheck calculator","pa paycheck calculator","paycheck calculator pa"]},
  {slug:"south-carolina-paycheck-calculator",name:"South Carolina",short:"SC",rate:5.5,aliases:["sc paycheck calculator"]},
  {slug:"tennessee-paycheck-calculator",name:"Tennessee",short:"TN",rate:0,noTax:true,aliases:["tennessee paycheck calculator","tn paycheck calculator","paycheck calculator tn"]},
  {slug:"texas-paycheck-calculator",name:"Texas",short:"TX",rate:0,noTax:true,aliases:["texas paycheck calculator","paycheck calculator texas"]},
  {slug:"utah-paycheck-calculator",name:"Utah",short:"UT",rate:4.45,aliases:["utah paycheck calculator"]},
  {slug:"virginia-paycheck-calculator",name:"Virginia",short:"VA",rate:5.75,aliases:["virginia paycheck calculator","va paycheck calculator"]},
  {slug:"washington-paycheck-calculator",name:"Washington",short:"WA",rate:0,noTax:true,aliases:["washington paycheck calculator","washington state paycheck calculator","paycheck calculator washington"]},
  {slug:"wisconsin-paycheck-calculator",name:"Wisconsin",short:"WI",rate:5.3,aliases:["wisconsin paycheck calculator"]},
  {slug:"alaska-paycheck-calculator",name:"Alaska",short:"AK",rate:0,noTax:true,aliases:["alaska paycheck calculator"]},
  {slug:"delaware-paycheck-calculator",name:"Delaware",short:"DE",rate:5.55,aliases:["delaware paycheck calculator"]},
  {slug:"washington-dc-paycheck-calculator",name:"Washington DC",seoName:"DC",short:"DC",rate:6.5,aliases:["dc paycheck calculator", "washington dc paycheck calculator"]},
  {slug:"maine-paycheck-calculator",name:"Maine",short:"ME",rate:6.75,aliases:["maine paycheck calculator", "paycheck calculator maine"]},
  {slug:"mississippi-paycheck-calculator",name:"Mississippi",short:"MS",rate:4,aliases:["mississippi paycheck calculator", "ms paycheck calculator", "paycheck calculator mississippi"]},
  {slug:"montana-paycheck-calculator",name:"Montana",short:"MT",rate:4.7,aliases:["montana paycheck calculator"]},
  {slug:"nh-paycheck-calculator",name:"New Hampshire",seoName:"NH",short:"NH",rate:0,noTax:true,aliases:["nh paycheck calculator", "new hampshire paycheck calculator", "paycheck calculator nh"]},
  {slug:"new-mexico-paycheck-calculator",name:"New Mexico",short:"NM",rate:4.7,aliases:["new mexico paycheck calculator", "nm paycheck calculator", "paycheck calculator new mexico"]},
  {slug:"north-dakota-paycheck-calculator",name:"North Dakota",short:"ND",rate:1.95,aliases:["north dakota paycheck calculator"]},
  {slug:"rhode-island-paycheck-calculator",name:"Rhode Island",short:"RI",rate:3.75,aliases:["rhode island paycheck calculator", "ri paycheck calculator", "paycheck calculator rhode island"]},
  {slug:"south-dakota-paycheck-calculator",name:"South Dakota",short:"SD",rate:0,noTax:true,aliases:["south dakota paycheck calculator"]},
  {slug:"vermont-paycheck-calculator",name:"Vermont",short:"VT",rate:3.35,aliases:["vermont paycheck calculator"]},
  {slug:"wv-paycheck-calculator",name:"West Virginia",seoName:"WV",short:"WV",rate:4.22,aliases:["wv paycheck calculator", "paycheck calculator wv", "west virginia paycheck calculator"]},
  {slug:"wyoming-paycheck-calculator",name:"Wyoming",short:"WY",rate:0,noTax:true,aliases:["wyoming paycheck calculator"]},
];
export const locationBySlug = Object.fromEntries(locations.map(x=>[x.slug,x]));
