"use client";
import { useMemo, useState } from "react";
import { estimateAnnualPay, money, wholeMoney, type FilingStatus } from "../lib/payroll";

export default function BonusCommissionCalculator() {
  const [salary,setSalary]=useState(65000), [bonus,setBonus]=useState(5000), [commission,setCommission]=useState(8000), [preTax,setPreTax]=useState(3000);
  const [status,setStatus]=useState<FilingStatus>("single");
  const result=useMemo(()=>{const gross=Math.max(0,salary)+Math.max(0,bonus)+Math.max(0,commission);return {gross,...estimateAnnualPay(gross,status,Math.min(gross,Math.max(0,preTax)))}},[salary,bonus,commission,preTax,status]);
  const tax=result.federal+result.socialSecurity+result.medicare;
  return <main><Header/><section className="hero subpage" id="top"><div className="eyebrow">★ TEXAS SUPPLEMENTAL PAY TOOL</div><h1>Texas Bonus &amp; <em>Commission Calculator</em></h1><p className="hero-copy">Estimate how a bonus or sales commission changes your annual take-home pay in Texas.</p>
    <div className="calculator"><section className="inputs"><div className="section-heading"><span className="step">1</span><div><h2>Enter annual pay</h2><p>Keep base pay and supplemental pay separate.</p></div></div>
      <MoneyField label="Base salary" value={salary} setValue={setSalary}/><div className="split-fields"><MoneyField label="Expected bonus" value={bonus} setValue={setBonus}/><MoneyField label="Expected commission" value={commission} setValue={setCommission}/></div>
      <label className="field"><span>Federal filing status</span><select value={status} onChange={e=>setStatus(e.target.value as FilingStatus)}><option value="single">Single</option><option value="married">Married filing jointly</option><option value="head">Head of household</option></select></label>
      <MoneyField label="Annual pre-tax deductions" value={preTax} setValue={setPreTax}/>
    </section><section className="results" aria-live="polite"><div className="section-heading light"><span className="step">2</span><div><h2>Estimated annual take-home</h2><p>Salary, bonus, and commission combined.</p></div></div><div className="net-amount"><span>ESTIMATED NET PAY</span><strong>{wholeMoney.format(result.net)}</strong><small>{money.format(result.net/12)} average per month</small></div><div className="breakdown"><div><span>Total gross pay</span><b>{wholeMoney.format(result.gross)}</b></div><div><span>Bonus + commission</span><b>{wholeMoney.format(bonus+commission)}</b></div><div><span>Estimated federal tax</span><b>−{wholeMoney.format(result.federal)}</b></div><div><span>Social Security + Medicare</span><b>−{wholeMoney.format(result.socialSecurity+result.medicare)}</b></div><div><span>All estimated taxes</span><b>−{wholeMoney.format(tax)}</b></div><div><span>Texas state income tax</span><b>$0</b></div></div><div className="result-note"><span>ⓘ</span><p>Actual bonus withholding may use a supplemental wage method. This annual estimate helps show your likely overall tax impact.</p></div></section></div></section>
    <section className="content-panel"><p className="kicker">BONUS TAXES IN TEXAS</p><h2>How are bonuses and commissions taxed?</h2><p>Texas does not levy individual state income tax, but bonuses and commissions are still subject to federal income tax, Social Security, and Medicare. A paycheck may show a different withholding rate than your final annual tax liability because employers can use special supplemental wage withholding rules.</p><div className="tool-links"><a href="/"><b>Texas salary paycheck calculator</b><span>Calculate regular salary pay →</span></a><a href="/texas-hourly-paycheck-calculator"><b>Hourly & daily calculator</b><span>Estimate hourly take-home pay →</span></a></div></section><Footer/></main>
}
function MoneyField({label,value,setValue}:{label:string,value:number,setValue:(v:number)=>void}){return <label className="field"><span>{label}</span><div className="money-input"><span>$</span><input type="number" min="0" step="500" value={value} onChange={e=>setValue(Number(e.target.value))}/></div></label>}
function Header(){return <header className="site-header"><a className="brand" href="/"><span className="brand-mark">★</span><span>Lone Star <b>Paycheck</b></span></a><nav><a href="/">Salary</a><a href="/texas-bonus-commission-paycheck-calculator">Bonus & commission</a><a href="/texas-hourly-paycheck-calculator">Hourly</a></nav><span className="year-pill">Updated for 2026</span></header>}
function Footer(){return <footer><a className="brand" href="/"><span className="brand-mark">★</span><span>Lone Star <b>Paycheck</b></span></a><p>Free Texas paycheck estimates, built for clarity.</p><p className="disclaimer">For informational purposes only. Not tax, legal, or financial advice.</p></footer>}
