"use client";
import { useMemo,useState } from "react";
import { estimateAnnualPay,money,wholeMoney,type FilingStatus } from "../lib/payroll";
import type { LocationInfo } from "../lib/locations";
import { locations } from "../lib/locations";

const payPeriods={weekly:52,"bi-weekly":26,"semi-monthly":24,monthly:12};
export default function LocationCalculator({place}:{place:LocationInfo}){
 const [salary,setSalary]=useState(70000),[status,setStatus]=useState<FilingStatus>("single"),[frequency,setFrequency]=useState<keyof typeof payPeriods>("bi-weekly"),[preTax,setPreTax]=useState(200),[stateRate,setStateRate]=useState(place.rate);
 const [query,setQuery]=useState("");
 const r=useMemo(()=>{const periods=payPeriods[frequency],annualPre=Math.min(salary,preTax*periods),base=estimateAnnualPay(Math.max(0,salary),status,annualPre),stateTax=Math.max(0,salary-annualPre)*Math.max(0,stateRate)/100;return {...base,periods,annualPre,stateTax,net:Math.max(0,base.net-stateTax)}},[salary,status,frequency,preTax,stateRate]);
 const href=(x:LocationInfo)=>`/${x.slug}`;
 const matches=locations.filter(x=>`${x.name} ${x.short}`.toLowerCase().includes(query.toLowerCase())).slice(0,8);
 return <div className="state-tool-shell" id="calculator">
  <div className="state-picker"><div><span className="picker-label">SELECT A PAYCHECK CALCULATOR</span><b>Calculate pay in another state</b></div><div className="state-search"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Search states — current: ${place.name}`} aria-label="Search paycheck calculators by state"/>{query&&<div className="state-options">{matches.map(x=><a key={x.slug} href={href(x)}><span>{x.name}</span><small>{x.short}</small></a>)}{!matches.length&&<p>No matching state</p>}</div>}</div><select aria-label="Select state paycheck calculator" value={place.slug} onChange={e=>{const x=locations.find(l=>l.slug===e.target.value);if(x)window.location.href=href(x)}}>{locations.map(x=><option key={x.slug} value={x.slug}>{x.name}</option>)}</select></div>
  <div className="state-calculator-card"><section className="inputs"><div className="section-heading"><span className="step">1</span><div><h2>Your {place.short} pay details</h2><p>Enter income, pay schedule, and deductions.</p></div></div>
  <label className="field"><span>Annual gross salary</span><div className="money-input"><span>$</span><input type="number" min="0" value={salary} onChange={e=>setSalary(Number(e.target.value))}/></div></label>
  <div className="split-fields"><label className="field"><span>Pay frequency</span><select value={frequency} onChange={e=>setFrequency(e.target.value as keyof typeof payPeriods)}>{Object.keys(payPeriods).map(x=><option key={x}>{x}</option>)}</select></label><label className="field"><span>Federal filing status</span><select value={status} onChange={e=>setStatus(e.target.value as FilingStatus)}><option value="single">Single</option><option value="married">Married filing jointly</option><option value="head">Head of household</option></select></label></div>
  <div className="split-fields"><label className="field"><span>Pre-tax deductions / paycheck</span><div className="money-input"><span>$</span><input type="number" min="0" value={preTax} onChange={e=>setPreTax(Number(e.target.value))}/></div></label><label className="field"><span>Estimated state/local tax rate</span><div className="money-input suffix"><input type="number" min="0" step=".1" value={stateRate} onChange={e=>setStateRate(Number(e.target.value))}/><span>%</span></div><small>Editable planning rate, not an official withholding table</small></label></div>
 </section><section className="results" aria-live="polite"><div className="section-heading light"><span className="step">2</span><div><h2>Estimated take-home pay</h2><p>{place.name} planning estimate for 2026.</p></div></div><div className="net-amount"><span>NET PAY · {frequency.toUpperCase()}</span><strong>{money.format(r.net/r.periods)}</strong><small>{wholeMoney.format(r.net)} per year</small></div><div className="breakdown"><div><span>Gross pay</span><b>{money.format(salary/r.periods)}</b></div><div><span>Federal income tax</span><b>−{money.format(r.federal/r.periods)}</b></div><div><span>Social Security</span><b>−{money.format(r.socialSecurity/r.periods)}</b></div><div><span>Medicare</span><b>−{money.format(r.medicare/r.periods)}</b></div><div><span>{place.name} state/local estimate</span><b>−{money.format(r.stateTax/r.periods)}</b></div><div><span>Pre-tax deductions</span><b>−{money.format(r.annualPre/r.periods)}</b></div></div><div className="result-note"><span>ⓘ</span><p>{place.noTax?`${place.name} does not impose a broad individual income tax on wages; other payroll deductions can still apply.`:`The editable ${stateRate}% rate is a planning shortcut. Actual ${place.name} withholding depends on current forms, brackets, credits, and local rules.`}</p></div></section></div>
 </div>
}
