"use client";
import { useMemo, useState } from "react";
import { estimateAnnualPay, money, wholeMoney, type FilingStatus } from "../lib/payroll";

export default function HourlyCalculator(){
  const [rate,setRate]=useState(25),[hours,setHours]=useState(40),[overtime,setOvertime]=useState(5),[days,setDays]=useState(5),[weeks,setWeeks]=useState(52),[preTax,setPreTax]=useState(100),[status,setStatus]=useState<FilingStatus>("single");
  const result=useMemo(()=>{const weekly=Math.max(0,rate)*(Math.max(0,hours)+Math.max(0,overtime)*1.5),gross=weekly*Math.max(0,weeks),annualPreTax=Math.min(gross,Math.max(0,preTax)*Math.max(0,weeks));return {weekly,gross,...estimateAnnualPay(gross,status,annualPreTax)}},[rate,hours,overtime,weeks,preTax,status]);
  return <main><Header/><section className="hero subpage"><div className="eyebrow">★ FREE HOURLY & DAILY TOOL</div><h1>Texas Hourly Paycheck <em>Calculator</em></h1><p className="hero-copy">Turn hourly or daily work into a clear Texas take-home pay estimate, including overtime.</p><div className="calculator"><section className="inputs"><div className="section-heading"><span className="step">1</span><div><h2>Your work schedule</h2><p>Enter a typical working week.</p></div></div><div className="split-fields"><NumberField label="Hourly rate" prefix="$" value={rate} setValue={setRate}/><NumberField label="Hours per week" value={hours} setValue={setHours}/></div><div className="split-fields"><NumberField label="Overtime hours" value={overtime} setValue={setOvertime}/><NumberField label="Days per week" value={days} setValue={setDays}/></div><div className="split-fields"><NumberField label="Paid weeks per year" value={weeks} setValue={setWeeks}/><NumberField label="Pre-tax / week" prefix="$" value={preTax} setValue={setPreTax}/></div><label className="field"><span>Federal filing status</span><select value={status} onChange={e=>setStatus(e.target.value as FilingStatus)}><option value="single">Single</option><option value="married">Married filing jointly</option><option value="head">Head of household</option></select></label></section>
    <section className="results"><div className="section-heading light"><span className="step">2</span><div><h2>Estimated take-home pay</h2><p>Based on 1.5× overtime pay.</p></div></div><div className="net-amount"><span>ESTIMATED WEEKLY NET PAY</span><strong>{money.format(result.net/weeks)}</strong><small>{wholeMoney.format(result.net)} per year</small></div><div className="mini-stats"><div><span>Daily gross</span><b>{money.format(result.weekly/Math.max(1,days))}</b></div><div><span>Bi-weekly net</span><b>{money.format(result.net/weeks*2)}</b></div></div><div className="breakdown"><div><span>Weekly gross pay</span><b>{money.format(result.weekly)}</b></div><div><span>Annual gross pay</span><b>{wholeMoney.format(result.gross)}</b></div><div><span>Federal income tax / year</span><b>−{wholeMoney.format(result.federal)}</b></div><div><span>FICA / year</span><b>−{wholeMoney.format(result.socialSecurity+result.medicare)}</b></div><div><span>Texas state income tax</span><b>$0</b></div></div></section></div></section>
    <section className="content-panel"><p className="kicker">HOURLY TO TAKE-HOME PAY</p><h2>A free hourly and daily paycheck calculator for Texas</h2><p>Your gross weekly pay includes regular hours plus overtime at 1.5 times the hourly rate. The calculator annualizes that pay, estimates federal and FICA taxes, then shows weekly, bi-weekly, daily, and annual figures. Texas state income tax remains $0.</p><div className="tool-links"><a href="/"><b>Texas salary calculator</b><span>Estimate salary take-home pay →</span></a><a href="/texas-bonus-commission-paycheck-calculator"><b>Bonus & commission calculator</b><span>Calculate supplemental earnings →</span></a></div></section><Footer/></main>
}
function NumberField({label,prefix,value,setValue}:{label:string,prefix?:string,value:number,setValue:(v:number)=>void}){return <label className="field"><span>{label}</span><div className="money-input">{prefix&&<span>{prefix}</span>}<input type="number" min="0" value={value} onChange={e=>setValue(Number(e.target.value))}/></div></label>}
function Header(){return <header className="site-header"><a className="brand" href="/"><span className="brand-mark">★</span><span>Paycheck <b>Atlas</b></span></a><nav><a href="/">Salary</a><a href="/texas-bonus-commission-paycheck-calculator">Bonus & commission</a><a href="/texas-hourly-paycheck-calculator">Hourly</a></nav><span className="year-pill">Updated for 2026</span></header>}
function Footer(){return <footer><a className="brand" href="/"><span className="brand-mark">★</span><span>Paycheck <b>Atlas</b></span></a><p>Free paycheck estimates, built for clarity.</p><p className="disclaimer">Estimates are for informational purposes only and are not tax, legal, accounting, payroll, or financial advice. <a href="/disclaimer">Read the full disclaimer.</a></p></footer>}
